// Generated by CoffeeScript 1.6.3
/*!
@author Branko Vukelic <branko@brankovukelic.com>
@license MIT
*/

var define,
  __slice = [].slice;

define = (function(root) {
  if (typeof root.define === 'function' && root.define.amd) {
    return root.define;
  } else {
    if (typeof module === 'object' && module.exports) {
      return function(factory) {
        return module.exports = factory();
      };
    } else {
      return function(factory) {
        return root.dahelpers = factory();
      };
    }
  }
})(this);

define(function() {
  var h, pad, tag, tags, _i, _len;
  h = {
    FIRST_CHAR: /\b([a-z])/gi,
    objAttrs: function(o) {
      var attrs, key;
      attrs = [];
      for (key in o) {
        if (o[key]) {
          attrs.push("" + key + "=\"" + (o[key].replace(/"/g, '\\"')) + "\"");
        }
      }
      return attrs.join(' ');
    },
    tag: function(name, content, attrs, silence) {
      var s;
      if (content == null) {
        content = '';
      }
      if (attrs == null) {
        attrs = null;
      }
      if (silence == null) {
        silence = false;
      }
      if (!name) {
        return '';
      }
      if (silence && ((content == null) || content.toString() === '')) {
        return '';
      }
      s = "<" + name;
      if (attrs) {
        s += " " + (h.objAttrs(attrs));
      }
      s += ">" + content + "</" + name + ">";
      return s;
    },
    plural: function(singular, plural, count) {
      if (!singular) {
        return '';
      }
      if (count == null) {
        count = plural;
        plural = singular + 's';
      }
      if (count === 1) {
        return singular;
      } else {
        return plural;
      }
    },
    capitalize: function(s) {
      if (!s) {
        return '';
      }
      return "" + (s[0].toUpperCase()) + s.slice(1);
    },
    titleCase: function(s) {
      if (!s) {
        return '';
      }
      return s.replace(h.FIRST_CHAR, function() {
        var groups, match;
        match = arguments[0], groups = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
        return groups[0].toUpperCase();
      });
    },
    format: function(s, format) {
      var chr, _i, _len;
      if (!s) {
        return '';
      }
      s = '' + s;
      if (!format) {
        return s;
      }
      s = s.split('');
      for (_i = 0, _len = s.length; _i < _len; _i++) {
        chr = s[_i];
        format = format.replace('#', chr);
      }
      return format;
    },
    reverse: function(s) {
      if (s) {
        return s.split('').reverse().join('');
      } else {
        return '';
      }
    },
    sgroup: function(s, n) {
      var m;
      if (s == null) {
        return [];
      }
      s = s.toString();
      if (!n) {
        return [s];
      }
      m = s.match(new RegExp("(.{1," + n + "})", 'g'));
      return m;
    },
    pad: pad = function(s, len, char, tail, separator) {
      var t, _ref;
      if (char == null) {
        char = '0';
      }
      if (tail == null) {
        tail = false;
      }
      if (separator == null) {
        separator = '.';
      }
      if (tail === false) {
        return ((new Array(len)).join(char) + s).slice(-len);
      } else {
        _ref = s.toString().split(separator), s = _ref[0], t = _ref[1];
        if (tail === 0) {
          return pad(s, len, char);
        } else {
          s = pad(s, len, char);
          t || (t = char);
          t = pad(h.reverse(t), tail, char);
          t = h.reverse(t);
          return [s, t].join(separator);
        }
      }
    },
    thousands: function(num, separator, decimalSeparator) {
      var frac, _ref;
      if (separator == null) {
        separator = ',';
      }
      if (decimalSeparator == null) {
        decimalSeparator = '.';
      }
      num = num.toString();
      num = num.replace(/[^\d\.-]/g, '');
      num = parseFloat(num);
      if (isNaN(num)) {
        return '';
      }
      _ref = num.toString().split('.'), num = _ref[0], frac = _ref[1];
      num = h.reverse(num);
      num = h.sgroup(num, 3).join(separator);
      num = h.reverse(num);
      if (frac) {
        num = "" + num + decimalSeparator + frac;
      }
      return num;
    },
    si: function(num, d, thousands, sep, decSep) {
      var adjustment, factor, idx, unit, units, _i, _len;
      if (d == null) {
        d = 0;
      }
      if (thousands == null) {
        thousands = false;
      }
      if (sep == null) {
        sep = ",";
      }
      if (decSep == null) {
        decSep = '.';
      }
      if (num == null) {
        return '';
      }
      units = 'kMGTPEZ'.split('');
      units.unshift('');
      adjustment = Math.pow(10, d);
      num = num * adjustment;
      factor = 0;
      for (idx = _i = 0, _len = units.length; _i < _len; idx = ++_i) {
        unit = units[idx];
        if (num % 1000) {
          num = num / adjustment;
          if (thousands) {
            num = h.thousands(num, sep, decSep);
          }
          return "" + num + unit;
        } else {
          num = num / 1000;
        }
      }
    },
    digits: function(s) {
      if (s == null) {
        return '';
      }
      return s.toString().replace(/[^\d]/g, '');
    },
    prefix: function(num, prefix) {
      if (num == null) {
        return '';
      }
      num = num.toString();
      if (!prefix) {
        return num;
      }
      if (num[0] === '-') {
        return "-" + prefix + num.slice(1);
      } else {
        return "" + prefix + num;
      }
    },
    round: function(num, d) {
      if (d == null) {
        d = 0;
      }
      num = parseFloat(num);
      if (isNaN(num)) {
        return 0;
      }
      return Math.round(num * Math.pow(10, d)) / Math.pow(10, d);
    },
    currency: function(num, currency, dec, sep, decSep, si) {
      if (currency == null) {
        currency = '$';
      }
      if (dec == null) {
        dec = 2;
      }
      if (sep == null) {
        sep = ',';
      }
      if (decSep == null) {
        decSep = '.';
      }
      if (si == null) {
        si = false;
      }
      if (si) {
        num = h.si(num, dec);
      } else {
        num = h.round(num, dec);
        num = h.thousands(num, sep, decSep);
        num = h.pad(num, 0, '0', dec, decSep);
      }
      return h.prefix(num, currency);
    },
    siCurrency: function(num, currency, dec, sep, decSep) {
      return h.currency(num, currency, dec, sep, decSep, true);
    },
    dollars: function(num, dec, si) {
      return h.currency(num, '$', dec, null, null, si);
    },
    yen: function(num, dec, sep, decSep, si) {
      return h.currency(num, '¥', dec, null, null, si);
    },
    pounds: function(num, dec, si) {
      return h.currency(num, '£', dec, null, null, si);
    }
  };
  tags = 'a p strong em ul ol li div span'.split(' ');
  for (_i = 0, _len = tags.length; _i < _len; _i++) {
    tag = tags[_i];
    h[tag] = (function(tag) {
      return function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        args.unshift(tag);
        return h.tag.apply(h, args);
      };
    })(tag);
  }
  return h;
});
